# Generated by Django 3.2 on 2021-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('publicacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
